// <auto-generated />
using System;
using Finance.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(FinanceDbContext))]
    [Migration("20260414223015_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Finance.Core.Domain.Investimento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DataVencimento")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Instituicao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Liquidez")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("SaldoAtual")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("TaxaRendimento")
                        .HasColumnType("numeric");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipoRentabilidade")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ValorAplicado")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ValorRetirado")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Investimentos", (string)null);
                });

            modelBuilder.Entity("Finance.Core.Domain.Movimentacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("Fixa")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("GrupoRecorrenciaId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("InvestimentoId")
                        .HasColumnType("uuid");

                    b.Property<int>("Periodo")
                        .HasColumnType("integer");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Movimentacoes");

                    b.HasDiscriminator<string>("Tipo");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Finance.Core.Domain.TransacaoInvestimento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("InvestimentoId")
                        .HasColumnType("uuid");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("InvestimentoId");

                    b.ToTable("TransacoesInvestimento");
                });

            modelBuilder.Entity("Finance.Core.Domain.Entrada", b =>
                {
                    b.HasBaseType("Finance.Core.Domain.Movimentacao");

                    b.HasDiscriminator().HasValue("Entrada");
                });

            modelBuilder.Entity("Finance.Core.Domain.Saida", b =>
                {
                    b.HasBaseType("Finance.Core.Domain.Movimentacao");

                    b.HasDiscriminator().HasValue("Saida");
                });

            modelBuilder.Entity("Finance.Core.Domain.TransacaoInvestimento", b =>
                {
                    b.HasOne("Finance.Core.Domain.Investimento", "Investimento")
                        .WithMany("Transacoes")
                        .HasForeignKey("InvestimentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Investimento");
                });

            modelBuilder.Entity("Finance.Core.Domain.Investimento", b =>
                {
                    b.Navigation("Transacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
