// <auto-generated />
using System;
using Finance.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(FinanceDbContext))]
    [Migration("20260602211520_AllowUpToThreeActiveCards")]
    partial class AllowUpToThreeActiveCards
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Finance.Core.Domain.CartaoBackfillExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExecutedAtUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ExecutedBy")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Modo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("SourceExecutionId")
                        .HasColumnType("uuid");

                    b.Property<int>("TotalAmbiguo")
                        .HasColumnType("integer");

                    b.Property<int>("TotalAnalisado")
                        .HasColumnType("integer");

                    b.Property<int>("TotalAplicado")
                        .HasColumnType("integer");

                    b.Property<int>("TotalAplicavel")
                        .HasColumnType("integer");

                    b.Property<int>("TotalIgnorado")
                        .HasColumnType("integer");

                    b.Property<int>("TotalRevertido")
                        .HasColumnType("integer");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SourceExecutionId");

                    b.HasIndex("UsuarioId", "ExecutedAtUtc");

                    b.ToTable("CartaoBackfillExecutions", (string)null);
                });

            modelBuilder.Entity("Finance.Core.Domain.CartaoBackfillExecutionItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CartaoId")
                        .HasColumnType("uuid");

                    b.Property<int?>("CompetenciaAplicada")
                        .HasColumnType("integer");

                    b.Property<int?>("CompetenciaOriginal")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DataAplicada")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DataExtraida")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DataOriginal")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DescricaoOriginal")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("ExecutionId")
                        .HasColumnType("uuid");

                    b.Property<string>("MotivoStatus")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid>("MovimentacaoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("MovimentacaoId");

                    b.HasIndex("ExecutionId", "Status");

                    b.ToTable("CartaoBackfillExecutionItems", (string)null);
                });

            modelBuilder.Entity("Finance.Core.Domain.CartaoManual", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("DiaFechamento")
                        .HasColumnType("integer");

                    b.Property<int>("DiaVencimento")
                        .HasColumnType("integer");

                    b.Property<decimal>("LimiteTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "Ativo")
                        .HasFilter("\"Ativo\" = true");

                    b.ToTable("CartoesManuais", (string)null);
                });

            modelBuilder.Entity("Finance.Core.Domain.Categoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Cor")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<string>("Icone")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<bool>("IsGlobal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal?>("OrcamentoMensal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("Finance.Core.Domain.CategoriaOrcamentoUsuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoriaGlobalId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("OrcamentoMensal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaGlobalId");

                    b.HasIndex("UsuarioId", "CategoriaGlobalId")
                        .IsUnique();

                    b.ToTable("CategoriasOrcamentosUsuarios");
                });

            modelBuilder.Entity("Finance.Core.Domain.Investimento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DataVencimento")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Instituicao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Liquidez")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("SaldoAtual")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("TaxaRendimento")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipoRentabilidade")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("ValorAplicado")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("ValorRetirado")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Ativo");

                    b.ToTable("Investimentos");
                });

            modelBuilder.Entity("Finance.Core.Domain.Meta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Concluida")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("DataAlvo")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Metas");
                });

            modelBuilder.Entity("Finance.Core.Domain.Movimentacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CartaoId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CategoriaId")
                        .HasColumnType("uuid");

                    b.Property<int?>("CompetenciaFatura")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("Fixa")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("GrupoRecorrenciaId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("InvestimentoId")
                        .HasColumnType("uuid");

                    b.Property<int?>("Km")
                        .HasColumnType("integer");

                    b.Property<int>("Periodo")
                        .HasColumnType("integer");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipoMovimentacaoFixa")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("RecorrenteFixa");

                    b.Property<string>("TipoRecorrencia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid?>("VeiculoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CartaoId");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("CompetenciaFatura");

                    b.HasIndex("Data");

                    b.HasIndex("InvestimentoId");

                    b.HasIndex("Tipo");

                    b.HasIndex("VeiculoId");

                    b.ToTable("Movimentacoes");

                    b.HasDiscriminator<string>("Tipo");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Finance.Core.Domain.TransacaoInvestimento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("InvestimentoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("InvestimentoId");

                    b.ToTable("TransacoesInvestimento");
                });

            modelBuilder.Entity("Finance.Core.Domain.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Finance.Core.Domain.Veiculo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AlertaKm")
                        .HasColumnType("integer");

                    b.Property<int>("Ano")
                        .HasColumnType("integer");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("UltimoKmAlerta")
                        .HasColumnType("integer");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Veiculos");
                });

            modelBuilder.Entity("Finance.Core.Domain.Entrada", b =>
                {
                    b.HasBaseType("Finance.Core.Domain.Movimentacao");

                    b.HasDiscriminator().HasValue("Entrada");
                });

            modelBuilder.Entity("Finance.Core.Domain.Saida", b =>
                {
                    b.HasBaseType("Finance.Core.Domain.Movimentacao");

                    b.HasDiscriminator().HasValue("Saida");
                });

            modelBuilder.Entity("Finance.Core.Domain.CartaoBackfillExecutionItem", b =>
                {
                    b.HasOne("Finance.Core.Domain.CartaoBackfillExecution", null)
                        .WithMany("Itens")
                        .HasForeignKey("ExecutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Finance.Core.Domain.CategoriaOrcamentoUsuario", b =>
                {
                    b.HasOne("Finance.Core.Domain.Categoria", null)
                        .WithMany()
                        .HasForeignKey("CategoriaGlobalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Finance.Core.Domain.Movimentacao", b =>
                {
                    b.HasOne("Finance.Core.Domain.CartaoManual", null)
                        .WithMany()
                        .HasForeignKey("CartaoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Finance.Core.Domain.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Finance.Core.Domain.Investimento", null)
                        .WithMany()
                        .HasForeignKey("InvestimentoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Finance.Core.Domain.Veiculo", null)
                        .WithMany()
                        .HasForeignKey("VeiculoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("Finance.Core.Domain.TransacaoInvestimento", b =>
                {
                    b.HasOne("Finance.Core.Domain.Investimento", "Investimento")
                        .WithMany("Transacoes")
                        .HasForeignKey("InvestimentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Investimento");
                });

            modelBuilder.Entity("Finance.Core.Domain.CartaoBackfillExecution", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("Finance.Core.Domain.Investimento", b =>
                {
                    b.Navigation("Transacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
